### PR TITLE
fix(image): allow empty string for alt and title property

### LINKED ISSUE #248: No possibility to set empty alt and title
Thank you for this great library. I'm happy to use it in my project!
I stumbled upon one little imperfection.

#### Expected behavior
`<Avatar alt="" title="" name="ambassify"` -> ``

#### Current behavior
`<Avatar alt="" title="" name="ambassify"` -> `ambassify`

It's because `"" == false` and it's being checked [here](https://github.com/ambassify/react-avatar/blob/master/src/utils.js#L172)

#### Why is it bad?
It leads to repeated value which is bad for accessibility
```html
<h1>Ambassify</h1>
<img alt="ambassify" title="ambassify"/>
```
"Ambassify" is being repeated **2 times!**

#### Possible non-breaking solution
Add option to pass parameter which will cause in empty alt and title, e.g. `noDescription`, `noAccessibility`, `noAlternativeText`, `noAlt`

`<Avatar alt="" title="" name="ambassify" noDescription` -> ``

### PR DESCRIPTION
**Pull request by ritchiejacobs**
Resolves #248

### CODE REVIEW

File: src/utils.js [hunk 1]
```diff
@@ -172,7 +172,7 @@ function getNullableText(...args) {
         if (arg)
             return arg;
 
-        if (arg === false || arg === null)
+        if (arg === false || arg === null || arg === '')
```
Comment (JorgenEvens) [inline src/utils.js:175]: This should have been added to the `if (arg)` condition. I would consider an empty string to be a valid value that people  might want to set.

**Review by JorgenEvens — CHANGES_REQUESTED** [review]

File: src/utils.js (hunk 1 above)
Comment (ritchiejacobs) [reply src/utils.js]: updated

**Review by JorgenEvens — APPROVED** [review]

**Comment by JorgenEvens** [comment]
This PR has been included in the [5.0.3](https://github.com/ambassify/react-avatar/releases/tag/v5.0.3) release :tada:
